#!/bin/bash

echo "🎉 Setup Complete!"
echo ""
echo "✅ API dependencies installed"
echo "✅ Webapp dependencies installed"
echo "✅ Environment files created"
echo ""
echo "⚠️  IMPORTANT: Next Steps Required"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📋 STEP 1: Get a PostgreSQL Database"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Choose one of these FREE options:"
echo ""
echo "Option A: Neon (Recommended)"
echo "  1. Visit: https://neon.tech"
echo "  2. Sign up (free)"
echo "  3. Create a new project"
echo "  4. Copy the connection string"
echo ""
echo "Option B: Vercel Postgres"
echo "  1. Go to Vercel Dashboard"
echo "  2. Storage → Create Database → Postgres"
echo "  3. Copy the connection string"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📋 STEP 2: Configure Database URL"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Edit: api/.env"
echo "Replace DATABASE_URL with your actual connection string:"
echo ""
echo "  DATABASE_URL=postgresql://user:password@host:5432/database"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📋 STEP 3: Run Database Migrations"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "cd api"
echo "npm run drizzle:generate"
echo "npm run drizzle:migrate"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📋 STEP 4: Start the Servers"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Terminal 1 - API:"
echo "  cd api"
echo "  npm run dev"
echo ""
echo "Terminal 2 - Webapp:"
echo "  cd webapp"
echo "  npm run dev"
echo ""
echo "Terminal 3 - Generate Mock Data:"
echo "  ./generate_mock_data.sh"
echo "  # OR"
echo "  python3 simulate_sensor.py"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📋 STEP 5: View Your Dashboard"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Open your browser:"
echo "  🌐 Webapp: http://localhost:5173"
echo "  🔌 API: http://localhost:3000"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📚 Need Help?"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  📖 Quick Start: QUICKSTART.md"
echo "  🧪 API Testing: TESTING.md"
echo "  🚀 Deployment: DEPLOYMENT.md"
echo "  📝 Submission: SUBMISSION_CHECKLIST.md"
echo ""
echo "Good luck with your assignment! 🚀"
echo ""
